version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MED_PG_URL: asd
      MED_ENV: production
      MED_JWT_SECRET: asd

volumes:
  psql_volume: