version: '3'

tasks:
  all:
    cmds:
      - task: build

  build:
    cmds:
      - echo "Building..."
      - go build -o main.exe cmd/dev/main.go

  run:
    cmds:
      - go run cmd/local/main.go

  docker-run:
    cmds:
      - docker-compose up -d

  docker-down:
    cmds:
      - docker-compose down

  test:
    cmds:
      - echo "Testing..."
      - go test ./... -v

  itest:
    cmds:
      - echo "Running integration tests..."
      - go test ./internal/database -v

  clean:
    cmds:
      - echo "Cleaning..."
      - rm -f main.exe

  watch:
    cmds:
      - air

  migrate:
    vars: 
      database: postgres://postgres:postgres@localhost:5435/postgres?sslmode=disable
    cmds:
      - bin/migrate -database {{.database}} -path migrations/ {{.CLI_ARGS}}

  swag:
    cmds:
      - swag init -d ".\cmd\{{.CLI_ARGS}}\,internal\tg_auth,internal/dto,internal/domain,internal/controller"
      - swag fmt 