basePath: /api
definitions:
  domain.Audio:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      owner:
        type: string
      path:
        type: string
    type: object
  dto.AudioDeletePayload:
    properties:
      id:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.UserResponse:
    properties:
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      photo_url:
        type: string
      role:
        type: string
      tg_id:
        type: integer
      username:
        type: string
    type: object
  tgauth.Credentials:
    properties:
      auth_date:
        type: integer
      first_name:
        type: string
      hash:
        type: string
      id:
        type: integer
      last_name:
        type: string
      photo_url:
        type: string
      username:
        type: string
    type: object
host: localhost:80
info:
  contact: {}
  description: Meditation API spec
  title: Meditation API
  version: 0.0.1
paths:
  /audio/{uuid}:
    get:
      parameters:
      - description: UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Audio'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerToken: []
      summary: GetAudio
      tags:
      - audio
  /audio/delete:
    delete:
      parameters:
      - description: Payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AudioDeletePayload'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerToken: []
      summary: DeleteAudio
      tags:
      - audio
  /audio/list:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Audio'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerToken: []
      summary: GetAudioList
      tags:
      - audio
  /audio/update:
    post:
      parameters:
      - description: Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Audio'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerToken: []
      summary: UpdateAudio
      tags:
      - audio
  /audio/upload:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Audio file
        in: formData
        name: file
        required: true
        type: file
      - in: formData
        name: description
        type: string
      - in: formData
        name: name
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerToken: []
      summary: UploadAudio
      tags:
      - audio
  /auth/telegram:
    post:
      parameters:
      - description: user creds
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/tgauth.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Telegram auth
      tags:
      - user
  /health:
    get:
      description: get API status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: API ststus
      tags:
      - health
  /me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - BearerToken: []
      summary: GetUser
      tags:
      - user
securityDefinitions:
  BearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
